# Generated by Django 5.0.6 on 2026-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='Jenis')),
                ('started_at', models.DateTimeField(verbose_name='Mulai')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Pulih')),
                ('notified', models.BooleanField(default=False, verbose_name='Terkirim ke Telegram')),
            ],
            options={
                'verbose_name': 'Gangguan',
                'verbose_name_plural': 'Gangguan',
                'db_table': 'alerts',
                'ordering': ['-started_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama pelanggan')),
                ('service_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID layanan')),
                ('monitor_type', models.CharField(choices=[('snmp_if', 'Interface fisik (dedicated)'), ('pppoe', 'Sesi PPPoE')], max_length=30, verbose_name='Tipe monitoring')),
                ('if_index', models.IntegerField(blank=True, help_text="Untuk interface fisik. Pakai tombol 'Cari interface' di halaman perangkat kalau belum tahu.", null=True, verbose_name='ifIndex')),
                ('if_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama interface')),
                ('pppoe_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username PPPoE')),
                ('threshold_bps', models.BigIntegerField(default=1000, help_text='Traffic in+out di bawah nilai ini dihitung sebagai down.', verbose_name='Ambang traffic (bps)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktif')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Belum diketahui')], default='unknown', editable=False, max_length=20, verbose_name='Status')),
                ('status_changed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Status berubah')),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
                'db_table': 'customers',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama perangkat')),
                ('ip', models.GenericIPAddressField(verbose_name='IP management')),
                ('vendor', models.CharField(choices=[('mikrotik', 'Mikrotik'), ('huawei', 'Huawei'), ('zte', 'ZTE'), ('generic', 'Lainnya')], default='generic', max_length=50, verbose_name='Vendor')),
                ('poll_method', models.CharField(choices=[('snmp', 'SNMP (interface fisik)'), ('mikrotik_api', 'Mikrotik API (PPPoE)')], default='snmp', max_length=30, verbose_name='Metode polling')),
                ('snmp_community', models.CharField(blank=True, default='public', help_text='Diisi kalau metode polling SNMP.', max_length=200, null=True, verbose_name='SNMP community')),
                ('snmp_port', models.IntegerField(blank=True, default=161, null=True, verbose_name='Port SNMP')),
                ('api_username', models.CharField(blank=True, help_text='User read-only Mikrotik. Jangan pakai admin.', max_length=200, null=True, verbose_name='User API')),
                ('api_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Password API')),
                ('api_port', models.IntegerField(blank=True, default=8728, null=True, verbose_name='Port API')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Perangkat',
                'verbose_name_plural': 'Perangkat',
                'db_table': 'devices',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
