# Generated by Django 5.0.6 on 2026-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama pekerjaan')),
                ('starts_at', models.DateTimeField(verbose_name='Mulai')),
                ('ends_at', models.DateTimeField(verbose_name='Selesai')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Dibuat oleh')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Dibuat')),
            ],
            options={
                'verbose_name': 'Jadwal pemeliharaan',
                'verbose_name_plural': 'Jadwal pemeliharaan',
                'db_table': 'maintenance_windows',
                'ordering': ['-starts_at'],
                'managed': False,
            },
        ),
    ]
